/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.owsb.view;

import com.mycompany.owsb.model.PurchaseManager;
import com.mycompany.owsb.model.SalesManager;
import com.mycompany.owsb.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author yyhao
 */
public class Admin_Dashboard extends javax.swing.JFrame {

    private User loggedInUser;
    
    // Declare without initializing
    private final SalesManager salesManager;
    private final PurchaseManager purchaseManager;

    /**
     * Creates new form Admin_Dashboard
     */
    public Admin_Dashboard(User loggedInUser) {
        this.loggedInUser = loggedInUser;
        this.salesManager = new SalesManager(loggedInUser);
        this.purchaseManager = new PurchaseManager(loggedInUser);
        initComponents();
        setLocationRelativeTo(null);

    }

    private void userManageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Open the Admin User Management page
        new Admin_UserManage(loggedInUser).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ManageSupplierButton = new javax.swing.JButton();
        ManageSalesButton = new javax.swing.JButton();
        PurchaseRequisitionButton = new javax.swing.JButton();
        AdminDashboardText = new javax.swing.JLabel();
        UserManagement = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        itemListBtn1 = new javax.swing.JButton();
        updateStockBtn = new javax.swing.JButton();
        stockReportBtn = new javax.swing.JButton();
        ViewPOButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ManageSupplierButton.setText("Manage Suppliers");
        ManageSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSupplierButtonActionPerformed(evt);
            }
        });

        ManageSalesButton.setText("Manage Sales");
        ManageSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSalesButtonActionPerformed(evt);
            }
        });

        PurchaseRequisitionButton.setText("Purchase Requisition");
        PurchaseRequisitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseRequisitionButtonActionPerformed(evt);
            }
        });

        AdminDashboardText.setFont(new java.awt.Font("Hiragino Sans", 1, 24)); // NOI18N
        AdminDashboardText.setText("Admin Dashboard");

        UserManagement.setText("User Management");
        UserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagementActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(51, 51, 51));
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        itemListBtn1.setText("Manage Item");
        itemListBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListBtn1ActionPerformed(evt);
            }
        });

        updateStockBtn.setText("Update Stock");
        updateStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockBtnActionPerformed(evt);
            }
        });

        stockReportBtn.setText("Stock Report");
        stockReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockReportBtnActionPerformed(evt);
            }
        });

        ViewPOButton.setText("Purchase Order");
        ViewPOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPOButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(196, 196, 196))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageSalesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PurchaseRequisitionButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(itemListBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateStockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stockReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ViewPOButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(AdminDashboardText)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AdminDashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(itemListBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(updateStockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageSalesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(stockReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PurchaseRequisitionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(ViewPOButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagementActionPerformed
        // TODO add your handling code here:
        userManageButtonActionPerformed(evt);
    }//GEN-LAST:event_UserManagementActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Closes the current SalesManagerWindow

        LoginWindow loginWindow = new LoginWindow();
        loginWindow.setVisible(true);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void itemListBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListBtn1ActionPerformed
        // TODO add your handling code here:
        Admin_ManageItem manageItemWindow = new Admin_ManageItem(salesManager);
        manageItemWindow.setVisible(true);
                
    }//GEN-LAST:event_itemListBtn1ActionPerformed

    private void updateStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockBtnActionPerformed

        new Admin_UpdateStockWindow(loggedInUser).setVisible(true);
    }//GEN-LAST:event_updateStockBtnActionPerformed

    private void stockReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockReportBtnActionPerformed
        // Options for the dialog
        String[] options = {"Overall Report", "Stock Movement Report"};

        // Show option dialog
        int choice = JOptionPane.showOptionDialog(
            null,
            "Choose report type:",
            "Stock Report Selection",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]
        );

        // Handle option without using switch
        if (choice == 0) {
            new Admin_StockReportWindow1(loggedInUser).setVisible(true);
        } else if (choice == 1) {
            new Admin_StockReportWindow2(loggedInUser).setVisible(true);
        }
    }//GEN-LAST:event_stockReportBtnActionPerformed

    private void ViewPOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPOButtonActionPerformed
        // TODO add your handling code here:
        Admin_ManagePurchaseOrder managePurchaseOrder = new Admin_ManagePurchaseOrder(purchaseManager);
        managePurchaseOrder.setVisible(true);
    }//GEN-LAST:event_ViewPOButtonActionPerformed

    private void ManageSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSupplierButtonActionPerformed
        // TODO add your handling code here:
        Admin_ManageSuppliersWindow manageSuppliersWindow = new Admin_ManageSuppliersWindow(salesManager);
        manageSuppliersWindow.setVisible(true);
    }//GEN-LAST:event_ManageSupplierButtonActionPerformed

    private void ManageSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSalesButtonActionPerformed
        // TODO add your handling code here:
        Admin_ManageSales manageSalesWindow = new Admin_ManageSales(salesManager);
        manageSalesWindow.setVisible(true);
    }//GEN-LAST:event_ManageSalesButtonActionPerformed

    private void PurchaseRequisitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseRequisitionButtonActionPerformed
        // TODO add your handling code here:
        Admin_PurchaseRequisition purchaseRequisitionWindow = new Admin_PurchaseRequisition(salesManager);
        purchaseRequisitionWindow.setVisible(true);
    }//GEN-LAST:event_PurchaseRequisitionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // You should not directly instantiate this class without a user
                // This is just to satisfy the method requirement
                // In practice, this window should only be opened via login
                System.out.println("Admin Dashboard should be opened via login with a valid user");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboardText;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ManageSalesButton;
    private javax.swing.JButton ManageSupplierButton;
    private javax.swing.JButton PurchaseRequisitionButton;
    private javax.swing.JButton UserManagement;
    private javax.swing.JButton ViewPOButton;
    private javax.swing.JButton itemListBtn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stockReportBtn;
    private javax.swing.JButton updateStockBtn;
    // End of variables declaration//GEN-END:variables
}
