package com.mycompany.owsb.view;

import com.mycompany.owsb.model.SalesManager;
import com.mycompany.owsb.model.User;
import com.mycompany.owsb.view.PurchaseManagerWindow;
import com.mycompany.owsb.view.FinanceManagerWindow;
import com.mycompany.owsb.view.InventoryManagerWindow;
import com.mycompany.owsb.view.SalesManagerWindow;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author timi
 */
public class LoginWindow extends javax.swing.JFrame {
    //find user by username
    private final String USERS_FILE = "data/user.txt";
    private java.util.List<User> users = loadUsers();
    
    //login user
    private User currentUser;
    
    //design panel
    private JPanel contentPanel;
    
    public LoginWindow() {
        loadUsers();
        initComponents();
        setBackgroundImage();
        setLocationRelativeTo(null);
    }
    
     private void setBackgroundImage() {
        // Load the image
        ImageIcon icon = new ImageIcon(getClass().getResource("/login_bg.png"));
        Image image = icon.getImage();

        // Create a custom panel to hold the background image
        JPanel backgroundPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        
        // Set the layout to null for absolute positioning
        backgroundPanel.setLayout(null);

        // Set the size of the background panel
        backgroundPanel.setPreferredSize(new Dimension(700, 500));

        // Set the custom panel as the content pane
        setContentPane(backgroundPanel);
        
        JLabel title = new JLabel("OMEGA WHOLESALE SDN BHD");
        title.setFont(new java.awt.Font("Heiti TC", java.awt.Font.BOLD, 16));
        
        
        // Re-add existing components to the background panel
        backgroundPanel.add(title);
        backgroundPanel.add(jLabel2);
        backgroundPanel.add(jLabel3);
        backgroundPanel.add(usernameField);
        backgroundPanel.add(passwordField);
        backgroundPanel.add(loginButton);

        // Set bounds for the components position (x, y, width, height)
        title.setBounds(240, 30, 400, 25);
        jLabel2.setBounds(450, 145, 80, 25);
        usernameField.setBounds(449, 165, 160, 25);
        jLabel3.setBounds(450, 205, 80, 25);
        passwordField.setBounds(449, 225, 160, 25);
        loginButton.setBounds(490, 275, 80, 30);
        
        loginButton.setBackground(Color.white);

        // Ensure the frame is repainted
        pack(); // Adjusts frame size based on the preferred size of the content pane
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel2.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        jLabel3.setText("Password");

        loginButton.setBackground(new java.awt.Color(204, 204, 255));
        loginButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        usernameField.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N

        passwordField.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginButton)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>  

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText().trim();
        String password = passwordField.getText().trim();

        User foundUser = null;

        // Loop through the list of users to find the matching user by username
        for (User user : users) {
            if (user.getUsername().equals(username)) {
                foundUser = user;
                break;
            }
        }

        if (foundUser == null) {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
            return;
        }


        if (foundUser.getPassword().equals(password)) {
            currentUser = foundUser;
            JOptionPane.showMessageDialog(this, "Login successful! \n" + foundUser.getRole() + " Role");
            openRoleBasedWindow(foundUser); // Open the appropriate window based on the user's role

        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password. ");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private java.util.List<User> loadUsers() {
        java.util.List<User> userList = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(USERS_FILE))) {
            String line;
            while ((line = reader.readLine()) != null) {
                User user = User.fromString(line);
                userList.add(user);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return userList;
    }

    private void saveUsers() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("user.txt"))) {
            for (User user : users) {
                bw.write(user.toString());
                bw.newLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error writing file: " + ex.getMessage());
        }
    }
    
    private void openRoleBasedWindow(User loggedInUser) {
        String role = loggedInUser.getRole();
        this.dispose(); // Close the login UI

        if ("Sales Manager".equals(role)) {
            SalesManager sm = new SalesManager();
            SalesManagerWindow window = new SalesManagerWindow(loggedInUser, sm);
            window.showSmWindow();
        } else if ("Purchase Manager".equals(role)) {
            new PurchaseManagerWindow(loggedInUser).setVisible(true);
        } else if ("Inventory Manager".equals(role)) {
            new InventoryManagerWindow(loggedInUser).setVisible(true);
        } else if ("Finance Manager".equals(role)) {
            new FinanceManagerWindow(loggedInUser).setVisible(true);
        } else if ("Administrator".equals(role)) {
            new AdminWindow(loggedInUser).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Unknown role: " + role, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
