/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.owsb.view;

import com.mycompany.owsb.model.Item;
import com.mycompany.owsb.model.PurchaseOrder;
import com.mycompany.owsb.model.SalesManager;
import com.mycompany.owsb.model.User;
import java.util.List;

/**
 *
 * @author timi
 */
public class SalesManagerWindow extends javax.swing.JFrame {
    // Store the currently logged-in user
    private final User loggedInUser;

    // Instance of SalesManager to call sales-related methods
    private final SalesManager salesManager;

    // List to hold all loaded purchase orders
    private List<PurchaseOrder> purchaseOrderList;
    private List<Item> itemList;


    /**
     * Creates new form SalesManagerWindow
     * @param loggedInUser
     * @param salesManager
     */
    public SalesManagerWindow(User loggedInUser, SalesManager salesManager) {
        this.loggedInUser = loggedInUser;
        this.salesManager = salesManager;
        initComponents();
        
        String username = loggedInUser.getUsername();
        loggedInUsernameLabel.setText("Welcome, " + username);
        
        // Check and update low stock button
        updateLowStockAlertButton();
    }
    
    // Method to show the UserWindow and ensure the user list is updated
    public void showSmWindow() {
        poDetails.setText("");
        loadPOsIntoList();
        setVisible(true);  // Show the window
    }
    
    // Method to load Purchase Orders from file and display them in the UI list
    private void loadPOsIntoList() {
        // Load the list of Purchase Orders from the purchase order file
        purchaseOrderList = PurchaseOrder.loadPurchaseOrders();
        
        // Update the JList and details area in the UI with the loaded Purchase Orders
        PurchaseOrder.updatePOListInUI(purchaseOrderList, poList, poDetails);
    }
    
    private void updateLowStockAlertButton() {
        itemList = Item.loadItems();
        
        int lowStockCount = 0;
        for (Item item : itemList) {
            if (Item.isLowStock(item.getStock())) {
                lowStockCount++;
            }
        }

        if (lowStockCount > 0) {
            lowStockAlertButton.setText("(" + lowStockCount + ")" + " Low Stock Alert !");
            lowStockAlertButton.setVisible(true);
        } else {
            lowStockAlertButton.setVisible(false);
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageItemsButton = new javax.swing.JButton();
        ManageSuppliersButton = new javax.swing.JButton();
        ManageDailySalesButton = new javax.swing.JButton();
        CreatePRButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        poDetails = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        poList = new javax.swing.JList<>();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        loggedInUsernameLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        lowStockAlertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Manager");

        ManageItemsButton.setBackground(new java.awt.Color(216, 178, 255));
        ManageItemsButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        ManageItemsButton.setText("Manage Items");
        ManageItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageItemsButtonActionPerformed(evt);
            }
        });

        ManageSuppliersButton.setBackground(new java.awt.Color(204, 153, 255));
        ManageSuppliersButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        ManageSuppliersButton.setText("Manage Suppliers");
        ManageSuppliersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSuppliersButtonActionPerformed(evt);
            }
        });

        ManageDailySalesButton.setBackground(new java.awt.Color(167, 126, 250));
        ManageDailySalesButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        ManageDailySalesButton.setText("Manage Daily Sales");
        ManageDailySalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDailySalesButtonActionPerformed(evt);
            }
        });

        CreatePRButton.setBackground(new java.awt.Color(153, 102, 255));
        CreatePRButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        CreatePRButton.setText("Manage Purchase Requisition");
        CreatePRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePRButtonActionPerformed(evt);
            }
        });

        poDetails.setEditable(false);
        poDetails.setColumns(20);
        poDetails.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        poDetails.setRows(5);
        jScrollPane1.setViewportView(poDetails);

        poList.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        poList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        poList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                poListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(poList);

        searchField.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(51, 51, 51));
        searchField.setText("Enter Purchase Order ID");
        searchField.setToolTipText("");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        loggedInUsernameLabel.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        loggedInUsernameLabel.setText("welcome username");

        logOutButton.setBackground(new java.awt.Color(51, 51, 51));
        logOutButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        lowStockAlertButton.setBackground(new java.awt.Color(255, 51, 0));
        lowStockAlertButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        lowStockAlertButton.setForeground(new java.awt.Color(255, 255, 255));
        lowStockAlertButton.setText("Low Stock Alert!");
        lowStockAlertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowStockAlertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loggedInUsernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lowStockAlertButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CreatePRButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(ManageDailySalesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageSuppliersButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageItemsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(loggedInUsernameLabel)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lowStockAlertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManageItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManageSuppliersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(ManageDailySalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageItemsButtonActionPerformed
        SmManageItemsWindow manageItemsWindow = new SmManageItemsWindow(this, salesManager);
        manageItemsWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_ManageItemsButtonActionPerformed

    private void ManageSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSuppliersButtonActionPerformed
        SmManageSuppliersWindow manageSuppliersWindow = new SmManageSuppliersWindow(this, salesManager);
        manageSuppliersWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_ManageSuppliersButtonActionPerformed

    private void CreatePRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePRButtonActionPerformed
        SmManagePrWindow createPrWindow = new SmManagePrWindow(this, salesManager);
        createPrWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_CreatePRButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //PurchaseOrder.searchAndDisplayPO(searchField, poDetails, purchaseOrderList);
        PurchaseOrder.searchAndDisplayPOInList(searchField, poDetails, purchaseOrderList);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        searchField.setText("");
    }//GEN-LAST:event_searchFieldMouseClicked

    private void ManageDailySalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDailySalesButtonActionPerformed
        SmManageDailySalesWindow manageDailySalesWindow = new SmManageDailySalesWindow(this);
        manageDailySalesWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_ManageDailySalesButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        this.dispose(); // Closes the current SalesManagerWindow

        LoginWindow loginWindow = new LoginWindow();
        loginWindow.setVisible(true);
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void lowStockAlertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowStockAlertButtonActionPerformed
        SmManageItemsWindow manageItemsWindow = new SmManageItemsWindow(this, salesManager);
        manageItemsWindow.setLowStockFilterChecked(true);  // set the checkbox to checked
        manageItemsWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_lowStockAlertButtonActionPerformed

    private void poListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_poListValueChanged
        // Load the list of Purchase Orders from the purchase order file
        purchaseOrderList = PurchaseOrder.loadPurchaseOrders();
        
        if (!evt.getValueIsAdjusting()) {  // only act on final selection
        String selectedPOID = poList.getSelectedValue();
        if (selectedPOID != null) {
            for (PurchaseOrder po : purchaseOrderList) {
                if (po.getOrderID().equals(selectedPOID)) {
                    String details = po.getFormattedDetails();
                    poDetails.setText(details);
                    break;
                }
            }
        }
    }
    }//GEN-LAST:event_poListValueChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatePRButton;
    private javax.swing.JButton ManageDailySalesButton;
    private javax.swing.JButton ManageItemsButton;
    private javax.swing.JButton ManageSuppliersButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel loggedInUsernameLabel;
    private javax.swing.JButton lowStockAlertButton;
    private javax.swing.JTextArea poDetails;
    private javax.swing.JList<String> poList;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
