/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.owsb.view;

import com.mycompany.owsb.model.PurchaseOrder;
import com.mycompany.owsb.model.SalesManager;
import com.mycompany.owsb.model.User;
import java.util.List;

/**
 *
 * @author timi
 */
public class SalesManagerWindow extends javax.swing.JFrame {
    // Store the currently logged-in user
    private final User loggedInUser;

    // Instance of SalesManager to call sales-related methods
    private final SalesManager salesManager;

    // List to hold all loaded purchase orders
    private List<PurchaseOrder> purchaseOrderList;

    // String representing the file path for purchase order data
    private static final String PO_FILE = "data/purchase_order.txt";

    /**
     * Creates new form SalesManagerWindow
     * @param loggedInUser
     * @param salesManager
     */
    public SalesManagerWindow(User loggedInUser, SalesManager salesManager) {
        this.loggedInUser = loggedInUser;
        this.salesManager = salesManager;
        initComponents();
    }
    
    // Method to show the UserWindow and ensure the user list is updated
    public void showSmWindow() {
        poDetails.setText("");
        loadPOsIntoList();
        setVisible(true);  // Show the window
    }
    
    // Method to load Purchase Orders from file and display them in the UI list
    private void loadPOsIntoList() {
        // Load the list of Purchase Orders from the purchase order file
        purchaseOrderList = PurchaseOrder.loadFromFile(PO_FILE);
        
        // Update the JList and details area in the UI with the loaded Purchase Orders
        PurchaseOrder.updatePOListInUI(purchaseOrderList, poList, poDetails);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageItemsButton = new javax.swing.JButton();
        ManageSuppliersButton = new javax.swing.JButton();
        ManageDailySalesButton = new javax.swing.JButton();
        CreatePRButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        poDetails = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        poList = new javax.swing.JList<>();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Manager");

        ManageItemsButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        ManageItemsButton.setText("Manage Items");
        ManageItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageItemsButtonActionPerformed(evt);
            }
        });

        ManageSuppliersButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        ManageSuppliersButton.setText("Manage Suppliers");
        ManageSuppliersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSuppliersButtonActionPerformed(evt);
            }
        });

        ManageDailySalesButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        ManageDailySalesButton.setText("Manage Daily Sales");
        ManageDailySalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDailySalesButtonActionPerformed(evt);
            }
        });

        CreatePRButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        CreatePRButton.setText("Manage Purchase Requisition");
        CreatePRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePRButtonActionPerformed(evt);
            }
        });

        poDetails.setEditable(false);
        poDetails.setColumns(20);
        poDetails.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        poDetails.setRows(5);
        jScrollPane1.setViewportView(poDetails);

        poList.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        poList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(poList);

        searchField.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(102, 102, 102));
        searchField.setText("Enter Purchase Order ID");
        searchField.setToolTipText("");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CreatePRButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(ManageDailySalesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageSuppliersButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageItemsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManageItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManageSuppliersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(ManageDailySalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageItemsButtonActionPerformed
        SmManageItemsWindow manageItemsWindow = new SmManageItemsWindow(this, salesManager);
        manageItemsWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_ManageItemsButtonActionPerformed

    private void ManageSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSuppliersButtonActionPerformed
        SmManageSuppliersWindow manageSuppliersWindow = new SmManageSuppliersWindow(this);
        manageSuppliersWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_ManageSuppliersButtonActionPerformed

    private void CreatePRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePRButtonActionPerformed
        SmManagePrWindow createPrWindow = new SmManagePrWindow(this);
        createPrWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_CreatePRButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        PurchaseOrder.searchAndDisplayPO(searchField, poDetails, purchaseOrderList);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        searchField.setText("");
    }//GEN-LAST:event_searchFieldMouseClicked

    private void ManageDailySalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDailySalesButtonActionPerformed
        SmManageDailySalesWindow manageDailySalesWindow = new SmManageDailySalesWindow(this);
        manageDailySalesWindow.setVisible(true);
        this.setVisible(false); // Hide current window
    }//GEN-LAST:event_ManageDailySalesButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatePRButton;
    private javax.swing.JButton ManageDailySalesButton;
    private javax.swing.JButton ManageItemsButton;
    private javax.swing.JButton ManageSuppliersButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea poDetails;
    private javax.swing.JList<String> poList;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
