/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.owsb.view;

import com.mycompany.owsb.model.Item;
import com.mycompany.owsb.model.PurchaseRequisition;
import com.mycompany.owsb.model.PurchaseRequisitionItem;
import com.mycompany.owsb.model.SalesManager;
import com.mycompany.owsb.model.Supplier;
import com.mycompany.owsb.model.SupplierItem;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author timi
 */
public class SmManagePrWindow extends javax.swing.JFrame {
    private final SalesManagerWindow parentWindow;
    
    private PurchaseRequisition pr;
    private SalesManager salesManager;
        
    
    private final String PR_FILE = "data/purchase_requisition.txt";

    private java.util.List<PurchaseRequisition> prDataList = new ArrayList<>();
    private java.util.List<PurchaseRequisitionItem> prItemDataList = new ArrayList<>();
    private java.util.List<Item> itemDataList = new ArrayList<>();
    private java.util.List<Supplier> supplierDataList = new ArrayList<>();
    private java.util.List<SupplierItem> supplierItemDataList = new ArrayList<>();

    /**
     * Creates new form NewJFrame
     * @param parentWindow
     */
    public SmManagePrWindow(SalesManagerWindow parentWindow, SalesManager salesManager) {
        this.parentWindow = parentWindow;
        this.salesManager = salesManager;
        initComponents();
        loadPRsIntoTable();
        setupWindowListener();        
    }
    
    // close button go back to menu instead of close system  
    private void setupWindowListener() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentWindow.showSmWindow(); // Show the homepage
                dispose(); // Close the current window
            }
        });
    }
    
    // Load PRs and their items, stitch them, display in table
    private void loadPRsIntoTable() {
        prDataList = PurchaseRequisition.loadPurchaseRequisition();
        prItemDataList = PurchaseRequisitionItem.loadPurchaseRequisitionItems();

        // Attach items to their parent PR
        for (PurchaseRequisitionItem item : prItemDataList) {
            for (PurchaseRequisition pr : prDataList) {
                if (pr.getPrID().equals(item.getPrID())) {
                    pr.addItem(item);
                    break;
                }
            }
        }

        // Update JTable with stitched data
        PurchaseRequisition.updatePRTableInUI(prDataList, prItemDataList, prTable);
    }


    // Prompt user for PR ID to edit
    private void promptForPRID() {
        String inputPRID = JOptionPane.showInputDialog(
            null,
            "Enter the Purchase Requisition ID to edit:",
            "PR ID",
            JOptionPane.PLAIN_MESSAGE
        );

        if (inputPRID != null && !inputPRID.trim().isEmpty()) {
            inputPRID = inputPRID.trim().toUpperCase();
            boolean found = false;

            // Search for the PR based on input ID
            for (PurchaseRequisition pr : prDataList) {
                if (pr.getPrID().equalsIgnoreCase(inputPRID)) {
                    salesManager.editPurchaseRequisition(this, prDataList, prTable); 
                    // Implement editPurchaseRequisition in SalesManager class

                    PurchaseRequisition.updatePRTableInUI(prDataList, prItemDataList, prTable); // Refresh table after edit
                    found = true;
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(null, "Purchase Requisition ID not found.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a valid Purchase Requisition ID.");
        }
    }


   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        prTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        addPRButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Requisition");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        prTable.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        prTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PR ID", "Item ID", "Quantity", "Required Date", "Supplier ID", "Raised By", "Unit Cost", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prTable.setGridColor(new java.awt.Color(102, 102, 102));
        prTable.setRowHeight(25);
        prTable.setSelectionBackground(new java.awt.Color(51, 51, 51));
        prTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(prTable);

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addPRButton.setBackground(new java.awt.Color(255, 51, 51));
        addPRButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        addPRButton.setForeground(new java.awt.Color(255, 255, 255));
        addPRButton.setText("Add");
        addPRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPRButtonActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        searchField.setForeground(new java.awt.Color(51, 51, 51));
        searchField.setText("Enter PR ID");
        searchField.setToolTipText("");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(102, 102, 102));
        searchButton.setFont(new java.awt.Font("Heiti TC", 0, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addPRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(searchField)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(addPRButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Update JTable to the latest
        PurchaseRequisition.updatePRTableInUI(prDataList, prItemDataList, prTable);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        searchField.setText("");
    }//GEN-LAST:event_searchFieldMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        PurchaseRequisition.searchAndDisplayPRInTable(searchField, prTable, prDataList, prItemDataList);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void addPRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPRButtonActionPerformed
        supplierDataList = Supplier.loadSuppliers();
        supplierItemDataList = SupplierItem.loadSupplierItems();
        itemDataList = Item.loadItems();
        salesManager.addPurchaseRequisition(this, itemDataList, prDataList, prItemDataList, supplierDataList, supplierItemDataList, prTable);
    }//GEN-LAST:event_addPRButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPRButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable prTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
